server:
  port: 5555
spring:
  application:
    name: router
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    consumer-service:
      path: /consumer/**
      serviceId: comsumer-service
    producer-service:
      path: /producer/**
      serciceId: producer-service
